import { IDeleteQozbCOntactData, IQOZBAssetFilter } from '@src/pages/QOZBS/qozbs'

export default {
	//Login Services
	login: (organizationId = 1): string => `/auth/sessions?organization_id=${organizationId}`,
	refreshToken: (): string => '/identity/token/refresh',
	forgotPassword: (): string => '/identity/forgot-password',
	verifyEmail: (): string => '/identity/verify-email',
	resetPassword: (): string => '/identity/reset-password',

	//users
	users: (query: string) => `/users?${query}`,
	createUser: () => '/user',
	editUser: () => '/user',
	roles: () => '/roles',
	getUser: (userId: string) => `/user/${userId}`,
	contactRoles: () => '/contact-roles',

	//funds
	funds: (query: string) => `/funds?${query}`,
	fundsQuestions: () => '/fund-questions',
	createFund: () => '/fund',
	createQuestionAnswers: () => '/fund/question-answers',
	editFund: (fundId: string) => `/fund/${fundId}`,
	editFundQuestionAnswers: () => '/fund/question-answers',
	fundTypes: () => '/fund-types',
	getFund: (fundId: string) => `/fund/${fundId}`,
	getFundQuestionAnswers: (fundId: string) => `/fund/${fundId}/question-answers`,
	deleteFund: (fundId: string) => `/fund/${fundId}`,
	activateFund: (fundId: string) => `/activate-fund/${fundId}`,
	deactivateFund: (fundId: string) => `/deactivate-fund/${fundId}`,
	fundEntityTypes: () => '/fund-entity-types',
	locations: () => '/locations',
	fundContacts: () => '/fund/contacts',
	deleteFundContact: ({ fundId, contactId }: { fundId: string; contactId: string }) =>
		`/fund/contact/${fundId}/${contactId}`,

	// QOZBS
	qozbs: (query: string) => `/qozbs?${query}`,
	getQozbQuestions: () => '/qozb/qozb-questions',
	createQozb: () => '/qozb',
	createQozbQuestionAnswers: () => '/qozb/question-answers',
	editQozb: (qozbId: string | number) => `/qozb/${qozbId}`,
	editQozbQuestionAnswers: () => '/qozb/question-answers',
	getQozb: (qozbId: string) => `/qozb/${qozbId}`,
	getQozbQuestionAnswers: (qozbId: string) => `/qozb/${qozbId}/question-answers`,
	qozbTypes: () => '/qozb-types',
	qozbLocations: () => '/qozbs/locations',
	deleteQozb: (qozbId: string) => `/qozb/${qozbId}`,
	qozbContacts: () => '/qozb/contacts',
	activateQozb: (qozbId: string) => `/activate-qozb/${qozbId}`,
	deactivateQozb: (qozbId: string) => `/deactivate-qozb/${qozbId}`,
	deleteQozbContact: ({ businessId, contactId }: IDeleteQozbCOntactData) => `/qozb/${businessId}/contact/${contactId}`,
	assetTypes: () => '/asset-types',
	allAssets: (query: string) => `/qozbs/assets?${query}`,
	getQozbAsset: (qozbId: string) => `/qozb/${qozbId}/assets`,
	postAsset: (qozbId: string) => `/qozb/${qozbId}/asset`,
	getAssetDetail: (assetId: string) => `/asset/${assetId}`,
	updateAsset: ({ qozbId, assetId }: IQOZBAssetFilter) => `/qozb/${qozbId}/asset/${assetId}`,
	deleteAsset: ({ qozbId, assetId }: IQOZBAssetFilter) => `/qozb/${qozbId}/asset/${assetId}`,
	activateAsset: ({ qozbId, assetId }: IQOZBAssetFilter) => `/qozb/${qozbId}/activate-asset/${assetId}`,
	deactivateAsset: ({ qozbId, assetId }: IQOZBAssetFilter) => `/qozb/${qozbId}/deactivate-asset/${assetId}`,
	getAssetQuestions: () => '/asset-questions',
	getAssetRelation: (assetId: string) => `/asset/${assetId}/questions-answers`,
	createOrUpdateAssetRelation: () => '/assets/questions-answers',

	//INVESTORS
	investors: (query: string) => `/investors?${query}`,
	createInvestor: () => '/investor',
	editInvestor: (investorId: string) => `/investor/${investorId}`,
	getInvestor: (investorId: string) => `/investor/${investorId}`,
	deleteInvestor: (investorId: string) => `/investor/${investorId}`,
	investorLocations: () => '/locations',
	investorContacts: () => '/investor/contacts',
	deleteInvestorContact: ({ investorId, contactId }: { investorId: string; contactId: string }) =>
		`/investor/contact/${investorId}/${contactId}`,

	//CapzoneIds
	capzoneIds: (query: string) => `/czids?${query}`,
	createCapzoneId: () => '/czids',
	editCapzoneId: (query: string) => `/czids?${query}`,
	getCapzoneId: (capzoneIdId: string) => `/czids/${capzoneIdId}`,
	deleteCapzoneId: (capzoneIdId: string) => `/czids/${capzoneIdId}`,
	activateCapzoneId: (capzoneIdId: string) => `/activate-czid/${capzoneIdId}`,
	deactivateCapzoneId: (capzoneIdId: string) => `/deactivate-czid/${capzoneIdId}`,
	allQozbs: () => '/qozbs-all',
	allFunds: () => '/funds-all',
	allInvestors: () => '/investors-all',
	allUsers: () => '/users-all',
	getInvestorQuestions: () => '/investor-questions',
	getInvestorRelations: (capzoneId: string) => `/czids/${capzoneId}/investor-relations`,
	updateInvestorQuestions: () => '/czids/investor-relations',
	getQOZBQuestions: () => '/qozb-questions',
	getQOZBRelations: (capzoneId: string) => `/czids/${capzoneId}/qozb-relations`,
	updateQOZBQuestions: () => '/czids/qozb-relations',
	getCZIDWithId: (id: string, query: string, type: 'fund' | 'investor' | 'qozb') => `/czids/${type}/${id}?${query}`,
}
